#define ABSOLUTE_ZERO                  0x0257
#define ACID_GREEN                     0xb5e3
#define AERO                           0x7ddd
#define AERO_BLUE                      0xc75a
#define AFRICAN_VIOLET                 0xb437
#define AIR_SUPERIORITY_BLUE           0x7518
#define ALABASTER                      0xef5c
#define ALICE_BLUE                     0xf7df
#define ALLOY_ORANGE                   0xc302
#define ALMOND                         0xeef9
#define AMARANTH                       0xe14a
#define AMARANTH_M_AND_P               0x994d
#define AMARANTH_PINK                  0xf4f7
#define AMARANTH_PURPLE                0xa929
#define AMARANTH_RED                   0xd105
#define AMAZON                         0x3bca
#define AMBER                          0xfde0
#define AMBER_SAE_ECE                  0xfbe0
#define AMETHYST                       0x9b39
#define ANDROID_GREEN                  0xa627
#define ANTIQUE_BRASS                  0xccae
#define ANTIQUE_BRONZE                 0x62e3
#define ANTIQUE_FUCHSIA                0x92f0
#define ANTIQUE_RUBY                   0x80c5
#define ANTIQUE_WHITE                  0xff5a
#define AO_ENGLISH                     0x0400
#define APPLE_GREEN                    0x8da0
#define APRICOT                        0xfe76
#define AQUA                           0x07ff
#define AQUAMARINE                     0x7ffa
#define ARCTIC_LIME                    0xd7e2
#define ARMY_GREEN                     0x4a84
#define ARTICHOKE                      0x8caf
#define ARYLIDE_YELLOW                 0xeead
#define ASH_GRAY                       0xb5f6
#define ASPARAGUS                      0x854d
#define ATOMIC_TANGERINE               0xfccc
#define AUBURN                         0xa145
#define AUREOLIN                       0xff60
#define AVOCADO                        0x5400
#define AZURE                          0x03ff
#define AZURE_X11_WEB_COLOR            0xf7ff
#define BABY_BLUE                      0x8e7e
#define BABY_BLUE_EYES                 0xa65e
#define BABY_PINK                      0xf618
#define BABY_POWDER                    0xffff
#define BAKER_MILLER_PINK              0xfc95
#define BANANA_MANIA                   0xff36
#define BARBIE_PINK                    0xd8d0
#define BARN_RED                       0x7840
#define BATTLESHIP_GREY                0x8430
#define BEAU_BLUE                      0xbebc
#define BEAVER                         0x9c0e
#define BEIGE                          0xf7bb
#define B_DAZZLED_BLUE                 0x2ad2
#define BIG_DIP_O_RUBY                 0x9928
#define BISQUE                         0xff38
#define BISTRE                         0x3943
#define BISTRE_BROWN                   0x9382
#define BITTER_LEMON                   0xcf01
#define BITTER_LIME                    0xbfe0
#define BITTERSWEET                    0xfb6b
#define BITTERSWEET_SHIMMER            0xba6a
#define BLACK                          0x0000
#define BLACK_BEAN                     0x3860
#define BLACK_CHOCOLATE                0x18c2
#define BLACK_COFFEE                   0x3965
#define BLACK_CORAL                    0x530d
#define BLACK_OLIVE                    0x39e6
#define BLACK_SHADOWS                  0xbd76
#define BLANCHED_ALMOND                0xff59
#define BLAST_OFF_BRONZE               0xa38c
#define BLEU_DE_FRANCE                 0x347c
#define BLIZZARD_BLUE                  0xaf3d
#define BLOND                          0xff97
#define BLOOD_RED                      0x6000
#define BLUE                           0x001f
#define BLUE_CRAYOLA                   0x1bbf
#define BLUE_MUNSELL                   0x0495
#define BLUE_NCS                       0x0437
#define BLUE_PANTONE                   0x00d5
#define BLUE_PIGMENT                   0x3193
#define BLUE_RYB                       0x023f
#define BLUE_BELL                      0xa51a
#define BLUE_GRAY                      0x64d9
#define BLUE_GREEN                     0x0cd7
#define BLUE_GREEN_COLOR_WHEEL         0x0268
#define BLUE_JEANS                     0x5d7d
#define BLUE_SAPPHIRE                  0x1310
#define BLUE_VIOLET                    0x895c
#define BLUE_VIOLET_CRAYOLA            0x7337
#define BLUE_VIOLET_COLOR_WHEEL        0x48cf
#define BLUE_YONDER                    0x5394
#define BLUETIFUL                      0x3b5c
#define BLUSH                          0xdaf0
#define BOLE                           0x7a27
#define BONE                           0xe6d9
#define BOTTLE_GREEN                   0x0349
#define BRANDY                         0x8207
#define BRICK_RED                      0xca0a
#define BRIGHT_GREEN                   0x67e0
#define BRIGHT_LILAC                   0xdc9d
#define BRIGHT_MAROON                  0xc109
#define BRIGHT_NAVY_BLUE               0x1bba
#define BRIGHT_YELLOW_CRAYOLA          0xfd43
#define BRILLIANT_ROSE                 0xfab4
#define BRINK_PINK                     0xfb0f
#define BRITISH_RACING_GREEN           0x0204
#define BRONZE                         0xcbe6
#define BROWN                          0x8aa1
#define BROWN_SUGAR                    0xab69
#define BRUNSWICK_GREEN                0x1a67
#define BUD_GREEN                      0x7dac
#define BUFF                           0xfe30
#define BURGUNDY                       0x8004
#define BURLYWOOD                      0xddd0
#define BURNISHED_BROWN                0xa3ce
#define BURNT_ORANGE                   0xcaa0
#define BURNT_SIENNA                   0xebaa
#define BURNT_UMBER                    0x8984
#define BYZANTINE                      0xb994
#define BYZANTIUM                      0x714c
#define CADET                          0x534e
#define CADET_BLUE                     0x5cf4
#define CADET_BLUE_CRAYOLA             0xad98
#define CADET_GREY                     0x9516
#define CADMIUM_GREEN                  0x0347
#define CADMIUM_ORANGE                 0xec25
#define CADMIUM_RED                    0xe004
#define CADMIUM_YELLOW                 0xffa0
#define CAFE_AU_LAIT                   0xa3cb
#define CAFE_NOIR                      0x49a4
#define CAMBRIDGE_BLUE                 0xa615
#define CAMEL                          0xc4cd
#define CAMEO_PINK                     0xedd9
#define CANARY                         0xfff3
#define CANARY_YELLOW                  0xff60
#define CANDY_APPLE_RED                0xf840
#define CANDY_PINK                     0xe38f
#define CAPRI                          0x05ff
#define CAPUT_MORTUUM                  0x5924
#define CARDINAL                       0xc0e7
#define CARIBBEAN_GREEN                0x0673
#define CARMINE                        0x9003
#define CARMINE_M_AND_P                0xd008
#define CARNATION_PINK                 0xfd39
#define CARNELIAN                      0xb0c3
#define CAROLINA_BLUE                  0x551a
#define CARROT_ORANGE                  0xec84
#define CASTLETON_GREEN                0x02a7
#define CATAWBA                        0x71a8
#define CEDAR_CHEST                    0xcac9
#define CELADON                        0xaf15
#define CELADON_BLUE                   0x03d4
#define CELADON_GREEN                  0x2c2f
#define CELESTE                        0xb7ff
#define CELTIC_BLUE                    0x2359
#define CERISE                         0xd98c
#define CERULEAN                       0x03d4
#define CERULEAN_BLUE                  0x2a97
#define CERULEAN_FROST                 0x6cd8
#define CERULEAN_CRAYOLA               0x1d7a
#define CG_BLUE                        0x03d4
#define CG_RED                         0xe1e6
#define CHAMPAGNE                      0xf739
#define CHAMPAGNE_PINK                 0xf6f9
#define CHARCOAL                       0x3229
#define CHARLESTON_GREEN               0x2145
#define CHARM_PINK                     0xe475
#define CHARTREUSE_TRADITIONAL         0xdfe0
#define CHARTREUSE_WEB                 0x7fe0
#define CHERRY_BLOSSOM_PINK            0xfdb8
#define CHESTNUT                       0x9226
#define CHILI_RED                      0xe1e5
#define CHINA_PINK                     0xdb74
#define CHINA_ROSE                     0xaa8d
#define CHINESE_RED                    0xa9c3
#define CHINESE_VIOLET                 0x8311
#define CHINESE_YELLOW                 0xfd80
#define CHOCOLATE_TRADITIONAL          0x79e0
#define CHOCOLATE_WEB                  0xd343
#define CHOCOLATE_COSMOS               0x5883
#define CHROME_YELLOW                  0xfd20
#define CINEREOUS                      0x9c0f
#define CINNABAR                       0xe206
#define CINNAMON_SATIN                 0xcb0f
#define CITRINE                        0xe681
#define CITRON                         0x9d43
#define CLARET                         0x78a6
#define COBALT_BLUE                    0x0235
#define COCOA_BROWN                    0xd343
#define COFFEE                         0x6a66
#define COLUMBIA_BLUE                  0xbedd
#define CONGO_PINK                     0xfc0f
#define COOL_GREY                      0x8c95
#define COPPER                         0xbb86
#define COPPER_CRAYOLA                 0xdc4c
#define COPPER_PENNY                   0xab6d
#define COPPER_RED                     0xcb6a
#define COPPER_ROSE                    0x9b2c
#define COQUELICOT                     0xf9c0
#define CORAL                          0xfbea
#define CORAL_PINK                     0xfc0f
#define CORDOVAN                       0x89e8
#define CORN                           0xff6b
#define CORNELL_RED                    0xb0c3
#define CORNFLOWER_BLUE                0x64bd
#define CORNSILK                       0xffdb
#define COSMIC_COBALT                  0x2971
#define COSMIC_LATTE                   0xffdc
#define COYOTE_BROWN                   0x8307
#define COTTON_CANDY                   0xfdfb
#define CREAM                          0xfffa
#define CRIMSON                        0xd8a7
#define CRIMSON_UA                     0x98c6
#define CRYSTAL                        0xa6db
#define CULTURED                       0xf7be
#define CYAN                           0x07ff
#define CYAN_PROCESS                   0x05bd
#define CYBER_GRAPE                    0x5a0f
#define CYBER_YELLOW                   0xfe80
#define CYCLAMEN                       0xf374
#define DARK_BLUE_GRAY                 0x6333
#define DARK_BROWN                     0x6204
#define DARK_BYZANTIUM                 0x59ca
#define DARK_CORNFLOWER_BLUE           0x2211
#define DARK_CYAN                      0x0451
#define DARK_ELECTRIC_BLUE             0x534f
#define DARK_GOLDENROD                 0xbc21
#define DARK_GREEN                     0x0184
#define DARK_GREEN_X11                 0x0320
#define DARK_JUNGLE_GREEN              0x1924
#define DARK_KHAKI                     0xbdad
#define DARK_LAVA                      0x49e6
#define DARK_LIVER                     0x5249
#define DARK_LIVER_HORSES              0x51e6
#define DARK_MAGENTA                   0x8811
#define DARK_MOSS_GREEN                0x4ae4
#define DARK_OLIVE_GREEN               0x5345
#define DARK_ORANGE                    0xfc60
#define DARK_ORCHID                    0x9999
#define DARK_PASTEL_GREEN              0x0607
#define DARK_PURPLE                    0x30c6
#define DARK_RED                       0x8800
#define DARK_SALMON                    0xecaf
#define DARK_SEA_GREEN                 0x8df1
#define DARK_SIENNA                    0x38a2
#define DARK_SKY_BLUE                  0x8dfa
#define DARK_SLATE_BLUE                0x49f1
#define DARK_SLATE_GRAY                0x2a69
#define DARK_SPRING_GREEN              0x1388
#define DARK_TURQUOISE                 0x067a
#define DARK_VIOLET                    0x901a
#define DARTMOUTH_GREEN                0x0387
#define DAVY_S_GREY                    0x52aa
#define DEEP_CERISE                    0xd990
#define DEEP_CHAMPAGNE                 0xfeb4
#define DEEP_CHESTNUT                  0xba69
#define DEEP_JUNGLE_GREEN              0x0249
#define DEEP_PINK                      0xf8b2
#define DEEP_SAFFRON                   0xfcc6
#define DEEP_SKY_BLUE                  0x05ff
#define DEEP_SPACE_SPARKLE             0x4b2d
#define DEEP_TAUPE                     0x7aec
#define DENIM                          0x1317
#define DENIM_BLUE                     0x2216
#define DESERT                         0xc4cd
#define DESERT_SAND                    0xee55
#define DIM_GRAY                       0x6b4d
#define DODGER_BLUE                    0x1c9f
#define DOGWOOD_ROSE                   0xd0cd
#define DRAB                           0x9382
#define DUKE_BLUE                      0x0013
#define DUTCH_WHITE                    0xeef7
#define EARTH_YELLOW                   0xe54b
#define EBONY                          0x52ea
#define ECRU                           0xc590
#define EERIE_BLACK                    0x18c3
#define EGGPLANT                       0x620a
#define EGGSHELL                       0xf75a
#define EGYPTIAN_BLUE                  0x11b4
#define EIGENGRAU                      0x10a3
#define ELECTRIC_BLUE                  0x7fdf
#define ELECTRIC_GREEN                 0x07e0
#define ELECTRIC_INDIGO                0x681f
#define ELECTRIC_LIME                  0xcfe0
#define ELECTRIC_PURPLE                0xb81f
#define ELECTRIC_VIOLET                0x881f
#define EMERALD                        0x564f
#define EMINENCE                       0x6990
#define ENGLISH_GREEN                  0x1a67
#define ENGLISH_LAVENDER               0xb412
#define ENGLISH_RED                    0xaa4a
#define ENGLISH_VERMILLION             0xca29
#define ENGLISH_VIOLET                 0x51eb
#define ERIN                           0x07e8
#define ETON_BLUE                      0x9654
#define FALLOW                         0xc4cd
#define FALU_RED                       0x80c3
#define FANDANGO                       0xb191
#define FANDANGO_PINK                  0xda90
#define FASHION_FUCHSIA                0xf014
#define FAWN                           0xe54e
#define FELDGRAU                       0x4aea
#define FERN_GREEN                     0x4bc8
#define FIELD_DRAB                     0x6aa3
#define FIERY_ROSE                     0xfaae
#define FIREBRICK                      0xb104
#define FIRE_ENGINE_RED                0xc905
#define FIRE_OPAL                      0xeae9
#define FLAME                          0xe2c4
#define FLAX                           0xeef0
#define FLIRT                          0xa00d
#define FLORAL_WHITE                   0xffde
#define FLUORESCENT_BLUE               0x17bd
#define FOREST_GREEN_CRAYOLA           0x5d2e
#define FOREST_GREEN_TRADITIONAL       0x0224
#define FOREST_GREEN_WEB               0x2444
#define FRENCH_BEIGE                   0xa3cb
#define FRENCH_BISTRE                  0x8369
#define FRENCH_BLUE                    0x0397
#define FRENCH_FUCHSIA                 0xf9f2
#define FRENCH_LILAC                   0x8311
#define FRENCH_LIME                    0x9fe7
#define FRENCH_MAUVE                   0xd39a
#define FRENCH_PINK                    0xfb73
#define FRENCH_RASPBERRY               0xc169
#define FRENCH_ROSE                    0xf251
#define FRENCH_SKY_BLUE                0x75bf
#define FRENCH_VIOLET                  0x8839
#define FROSTBITE                      0xe9b4
#define FUCHSIA                        0xf81f
#define FUCHSIA_CRAYOLA                0xc2b8
#define FUCHSIA_PURPLE                 0xc9cf
#define FUCHSIA_ROSE                   0xc20e
#define FULVOUS                        0xe420
#define FUZZY_WUZZY                    0x8203
#define GAINSBORO                      0xdefb
#define GAMBOGE                        0xe4c1
#define GENERIC_VIRIDIAN               0x03ec
#define GHOST_WHITE                    0xffdf
#define GLAUCOUS                       0x6416
#define GLOSSY_GRAPE                   0xac96
#define GO_GREEN                       0x054c
#define GOLD                           0xa3e0
#define GOLD_METALLIC                  0xd566
#define GOLD_WEB_GOLDEN                0xfea0
#define GOLD_CRAYOLA                   0xe5f1
#define GOLD_FUSION                    0x83a9
#define GOLDEN_BROWN                   0x9b22
#define GOLDEN_POPPY                   0xfe00
#define GOLDEN_YELLOW                  0xfee0
#define GOLDENROD                      0xdd24
#define GRANITE_GRAY                   0x632c
#define GRANNY_SMITH_APPLE             0xaf34
#define GRAY                           0x8410
#define GRAY_2                         0xbdf7
#define GREEN                          0x07e0
#define GREEN_CRAYOLA                  0x1d6f
#define GREEN_WEB                      0x0400
#define GREEN_MUNSELL                  0x054e
#define GREEN_NCS                      0x04ed
#define GREEN_PANTONE                  0x0568
#define GREEN_PIGMENT                  0x052a
#define GREEN_RYB                      0x6586
#define GREEN_BLUE                     0x1336
#define GREEN_BLUE_CRAYOLA             0x2c39
#define GREEN_CYAN                     0x04cc
#define GREEN_LIZARD                   0xa7a6
#define GREEN_SHEEN                    0x6d74
#define GREEN_YELLOW                   0xafe5
#define GREEN_YELLOW_CRAYOLA           0xf752
#define GRULLO                         0xacd0
#define GUNMETAL                       0x29a7
#define HAN_BLUE                       0x4379
#define HAN_PURPLE                     0x50df
#define HANSA_YELLOW                   0xeead
#define HARLEQUIN                      0x3fe0
#define HARVEST_GOLD                   0xdc80
#define HEAT_WAVE                      0xfbc0
#define HELIOTROPE                     0xdb9f
#define HELIOTROPE_GRAY                0xacd5
#define HOLLYWOOD_CERISE               0xf014
#define HONEYDEW                       0xf7fe
#define HONOLULU_BLUE                  0x0376
#define HOOKER_S_GREEN                 0x4bcd
#define HOT_MAGENTA                    0xf8f9
#define HOT_PINK                       0xfb56
#define HUNTER_GREEN                   0x32e7
#define ICEBERG                        0x753a
#define ICTERINE                       0xffab
#define ILLUMINATING_EMERALD           0x348e
#define IMPERIAL_RED                   0xe947
#define INCHWORM                       0xb76b
#define INDEPENDENCE                   0x4a8d
#define INDIA_GREEN                    0x1441
#define INDIAN_RED                     0xcaeb
#define INDIAN_YELLOW                  0xe54a
#define INDIGO                         0x4810
#define INDIGO_DYE                     0x020d
#define INTERNATIONAL_ORANGE_1         0xfa60
#define INTERNATIONAL_ORANGE_2         0xb8a1
#define INTERNATIONAL_ORANGE_3         0xc1a5
#define IRIS                           0x5a79
#define IRRESISTIBLE                   0xb22d
#define ISABELLINE                     0xf79d
#define ITALIAN_SKY_BLUE               0xb7ff
#define IVORY                          0xfffe
#define JADE                           0x054d
#define JAPANESE_CARMINE               0x9946
#define JAPANESE_VIOLET                0x598a
#define JASMINE                        0xfeef
#define JAZZBERRY_JAM                  0xa04b
#define JET                            0x31a6
#define JONQUIL                        0xf642
#define JUNE_BUD                       0xbeca
#define JUNGLE_GREEN                   0x2d50
#define KELLY_GREEN                    0x4dc2
#define KEPPEL                         0x3d93
#define KEY_LIME                       0xefb1
#define KHAKI_WEB                      0xc592
#define KHAKI_X11_LIGHT_KHAKI          0xf731
#define KOBE                           0x8962
#define KOBI                           0xe4f8
#define KOBICHA                        0x6a24
#define KOMBU_GREEN                    0x3206
#define KSU_PURPLE                     0x5151
#define LANGUID_LAVENDER               0xd65b
#define LAPIS_LAZULI                   0x2313
#define LASER_LEMON                    0xffec
#define LAUREL_GREEN                   0xadd3
#define LAVA                           0xc884
#define LAVENDER_FLORAL                0xb3fb
#define LAVENDER_WEB                   0xe73f
#define LAVENDER_BLUE                  0xce7f
#define LAVENDER_BLUSH                 0xff9e
#define LAVENDER_GRAY                  0xc61a
#define LAWN_GREEN                     0x7fe0
#define LEMON                          0xffa0
#define LEMON_CHIFFON                  0xffd9
#define LEMON_CURRY                    0xcd03
#define LEMON_GLACIER                  0xffe0
#define LEMON_MERINGUE                 0xf757
#define LEMON_YELLOW                   0xffa9
#define LEMON_YELLOW_CRAYOLA           0xfff3
#define LIBERTY                        0x52d4
#define LIGHT_BLUE                     0xaedc
#define LIGHT_CORAL                    0xf410
#define LIGHT_CORNFLOWER_BLUE          0x967d
#define LIGHT_CYAN                     0xe7ff
#define LIGHT_FRENCH_BEIGE             0xcd6f
#define LIGHT_GOLDENROD                0xffda
#define LIGHT_GRAY                     0xd69a
#define LIGHT_GREEN                    0x9772
#define LIGHT_ORANGE                   0xfed6
#define LIGHT_PERIWINKLE               0xc65c
#define LIGHT_PINK                     0xfdb8
#define LIGHT_SALMON                   0xfd0f
#define LIGHT_SEA_GREEN                0x2595
#define LIGHT_SKY_BLUE                 0x867f
#define LIGHT_SLATE_GRAY               0x7453
#define LIGHT_STEEL_BLUE               0xb63b
#define LIGHT_YELLOW                   0xfffc
#define LILAC                          0xcd19
#define LILAC_LUSTER                   0xacd5
#define LIME_COLOR_WHEEL               0xbfe0
#define LIME_WEB_X11_GREEN             0x07e0
#define LIME_GREEN                     0x3666
#define LINCOLN_GREEN                  0x1ac0
#define LINEN                          0xff9c
#define LION                           0xc4cd
#define LISERAN_PURPLE                 0xdb74
#define LITTLE_BOY_BLUE                0x6d1b
#define LIVER                          0x6268
#define LIVER_DOGS                     0xbb65
#define LIVER_ORGAN                    0x6963
#define LIVER_CHESTNUT                 0x9baa
#define LIVID                          0x64d9
#define MACARONI_AND_CHEESE            0xfdf1
#define MADDER_LAKE                    0xc986
#define MAGENTA                        0xf81f
#define MAGENTA_CRAYOLA                0xf294
#define MAGENTA_DYE                    0xc8ef
#define MAGENTA_PANTONE                0xd20f
#define MAGENTA_PROCESS                0xf812
#define MAGENTA_HAZE                   0x9a2e
#define MAGIC_MINT                     0xaf9a
#define MAGNOLIA                       0xf75a
#define MAHOGANY                       0xc200
#define MAIZE                          0xff6b
#define MAIZE_CRAYOLA                  0xf629
#define MAJORELLE_BLUE                 0x629b
#define MALACHITE                      0x0eca
#define MANATEE                        0x94d5
#define MANDARIN                       0xf3c9
#define MANGO                          0xfde0
#define MANGO_TANGO                    0xfc08
#define MANTIS                         0x760c
#define MARDI_GRAS                     0x8810
#define MARIGOLD                       0xed04
#define MAROON_CRAYOLA                 0xc109
#define MAROON_WEB                     0x8000
#define MAROON_X11                     0xb18c
#define MAUVE                          0xe59f
#define MAUVE_TAUPE                    0x92ed
#define MAUVELOUS                      0xecd5
#define MAXIMUM_BLUE                   0x4559
#define MAXIMUM_BLUE_GREEN             0x35f7
#define MAXIMUM_BLUE_PURPLE            0xad7c
#define MAXIMUM_GREEN                  0x5c66
#define MAXIMUM_GREEN_YELLOW           0xdf2a
#define MAXIMUM_PURPLE                 0x7190
#define MAXIMUM_RED                    0xd904
#define MAXIMUM_RED_PURPLE             0xa1cf
#define MAXIMUM_YELLOW                 0xffc6
#define MAXIMUM_YELLOW_RED             0xf5c9
#define MAY_GREEN                      0x4c88
#define MAYA_BLUE                      0x761f
#define MEDIUM_AQUAMARINE              0x66f5
#define MEDIUM_BLUE                    0x0019
#define MEDIUM_CANDY_APPLE_RED         0xe025
#define MEDIUM_CARMINE                 0xaa06
#define MEDIUM_CHAMPAGNE               0xf735
#define MEDIUM_ORCHID                  0xbaba
#define MEDIUM_PURPLE                  0x939b
#define MEDIUM_SEA_GREEN               0x3d8e
#define MEDIUM_SLATE_BLUE              0x7b5d
#define MEDIUM_SPRING_GREEN            0x07d3
#define MEDIUM_TURQUOISE               0x4e99
#define MEDIUM_VIOLET_RED              0xc0b0
#define MELLOW_APRICOT                 0xfdcf
#define MELLOW_YELLOW                  0xfeef
#define MELON                          0xfdd5
#define METALLIC_GOLD                  0xd566
#define METALLIC_SEAWEED               0x0bf1
#define METALLIC_SUNBURST              0x9be7
#define MEXICAN_PINK                   0xe00f
#define MIDDLE_BLUE                    0x7ebc
#define MIDDLE_BLUE_GREEN              0x8ed9
#define MIDDLE_BLUE_PURPLE             0x8b97
#define MIDDLE_GREY                    0x8c30
#define MIDDLE_GREEN                   0x4c6a
#define MIDDLE_GREEN_YELLOW            0xadec
#define MIDDLE_PURPLE                  0xdc16
#define MIDDLE_RED                     0xe46e
#define MIDDLE_RED_PURPLE              0xa28a
#define MIDDLE_YELLOW                  0xff40
#define MIDDLE_YELLOW_RED              0xed8e
#define MIDNIGHT                       0x712e
#define MIDNIGHT_BLUE                  0x18ce
#define MIDNIGHT_GREEN_EAGLE_GREEN     0x024a
#define MIKADO_YELLOW                  0xfe21
#define MIMI_PINK                      0xfedd
#define MINDARO                        0xe7d1
#define MING                           0x33af
#define MINION_YELLOW                  0xf70a
#define MINT                           0x3db1
#define MINT_CREAM                     0xf7ff
#define MINT_GREEN                     0x9ff3
#define MISTY_MOSS                     0xbdae
#define MISTY_ROSE                     0xff3c
#define MODE_BEIGE                     0x9382
#define MORNING_BLUE                   0x8d13
#define MOSS_GREEN                     0x8ccb
#define MOUNTAIN_MEADOW                0x35d1
#define MOUNTBATTEN_PINK               0x9bd1
#define MSU_GREEN                      0x1a27
#define MULBERRY                       0xc251
#define MULBERRY_CRAYOLA               0xca93
#define MUSTARD                        0xfecb
#define MYRTLE_GREEN                   0x33ce
#define MYSTIC                         0xd290
#define MYSTIC_MAROON                  0xaa0f
#define NADESHIKO_PINK                 0xf578
#define NAPLES_YELLOW                  0xfecb
#define NAVAJO_WHITE                   0xfef5
#define NAVY_BLUE                      0x0010
#define NAVY_BLUE_CRAYOLA              0x1bba
#define NEON_BLUE                      0x433f
#define NEON_CARROT                    0xfd08
#define NEON_GREEN                     0x3fe2
#define NEON_FUCHSIA                   0xfa0c
#define NEW_YORK_PINK                  0xd40f
#define NICKEL                         0x73ae
#define NON_PHOTO_BLUE                 0xa6fd
#define NYANZA                         0xeffb
#define OCEAN_BLUE                     0x4a16
#define OCEAN_GREEN                    0x4df2
#define OCHRE                          0xcba4
#define OLD_BURGUNDY                   0x4185
#define OLD_GOLD                       0xcda7
#define OLD_LACE                       0xffbc
#define OLD_LAVENDER                   0x7b4f
#define OLD_MAUVE                      0x6188
#define OLD_ROSE                       0xc410
#define OLD_SILVER                     0x8430
#define OLIVE                          0x8400
#define OLIVE_DRAB_1                   0x8417
#define OLIVE_DRAB_2                   0x01e6
#define OLIVE_GREEN                    0xb58b
#define OLIVINE                        0x9dce
#define ONYX                           0x31c7
#define OPAL                           0xae17
#define OPERA_MAUVE                    0xb434
#define ORANGE                         0xfbe0
#define ORANGE_CRAYOLA                 0xfba7
#define ORANGE_PANTONE                 0xfac0
#define ORANGE_WEB                     0xfd20
#define ORANGE_PEEL                    0xfce0
#define ORANGE_RED                     0xfb43
#define ORANGE_RED_CRAYOLA             0xfa89
#define ORANGE_SODA                    0xfac7
#define ORANGE_YELLOW                  0xf5e3
#define ORANGE_YELLOW_CRAYOLA          0xfead
#define ORCHID                         0xdb9a
#define ORCHID_PINK                    0xf5f9
#define ORCHID_CRAYOLA                 0xe4fa
#define OUTER_SPACE_CRAYOLA            0x29c7
#define OUTRAGEOUS_ORANGE              0xfb69
#define OXBLOOD                        0x8004
#define OXFORD_BLUE                    0x0108
#define OU_CRIMSON_RED                 0x80a2
#define PACIFIC_BLUE                   0x1d59
#define PAKISTAN_GREEN                 0x0320
#define PALATINATE_PURPLE              0x694c
#define PALE_AQUA                      0xbebc
#define PALE_CERULEAN                  0x9e3c
#define PALE_DOGWOOD                   0xebd3
#define PALE_PINK                      0xfedb
#define PALE_PURPLE_PANTONE            0xff3f
#define PALE_SILVER                    0xce17
#define PALE_SPRING_BUD                0xef57
#define PALE_VIOLET_RED                0xdb92
#define PANSY_PURPLE                   0x78c9
#define PAOLO_VERONESE_GREEN           0x04cf
#define PAPAYA_WHIP                    0xff7a
#define PARADISE_PINK                  0xe1ec
#define PARCHMENT                      0xf75a
#define PARIS_GREEN                    0x564f
#define PASTEL_PINK                    0xdd34
#define PATRIARCH                      0x8010
#define PAYNE_S_GREY                   0x534f
#define PEACH                          0xff36
#define PEACH_CRAYOLA                  0xfe54
#define PEACH_PUFF                     0xfed7
#define PEAR                           0xd706
#define PEARLY_PURPLE                  0xb354
#define PERIWINKLE                     0xce7f
#define PERIWINKLE_CRAYOLA             0xc67c
#define PERMANENT_GERANIUM_LAKE        0xe165
#define PERSIAN_BLUE                   0x19d7
#define PERSIAN_GREEN                  0x0532
#define PERSIAN_INDIGO                 0x308f
#define PERSIAN_ORANGE                 0xdc8b
#define PERSIAN_PINK                   0xf3f7
#define PERSIAN_PLUM                   0x70e3
#define PERSIAN_RED                    0xc986
#define PERSIAN_ROSE                   0xf954
#define PERSIMMON                      0xeac0
#define PEWTER_BLUE                    0x8d56
#define PHLOX                          0xd81f
#define PHTHALO_BLUE                   0x0071
#define PHTHALO_GREEN                  0x11a4
#define PICOTEE_BLUE                   0x2930
#define PICTORIAL_CARMINE              0xc049
#define PIGGY_PINK                     0xfefc
#define PINE_GREEN                     0x03cd
#define PINE_TREE                      0x2964
#define PINK                           0xfe19
#define PINK_PANTONE                   0xd252
#define PINK_FLAMINGO                  0xfbbf
#define PINK_LACE                      0xfefe
#define PINK_LAVENDER                  0xdd9a
#define PINK_SHERBET                   0xf474
#define PISTACHIO                      0x962e
#define PLATINUM                       0xe73c
#define PLUM                           0x8a30
#define PLUM_WEB                       0xdd1b
#define PLUMP_PURPLE                   0x5a36
#define POLISHED_PINE                  0x5d32
#define POMP_AND_POWER                 0x8311
#define POPSTAR                        0xba6c
#define PORTLAND_ORANGE                0xfac6
#define POWDER_BLUE                    0xb71c
#define PRINCETON_ORANGE               0xf404
#define PROCESS_YELLOW                 0xff60
#define PRUNE                          0x70e3
#define PRUSSIAN_BLUE                  0x018a
#define PSYCHEDELIC_PURPLE             0xd81f
#define PUCE                           0xcc53
#define PULLMAN_BROWN_UPS_BROWN        0x6202
#define PUMPKIN                        0xfba3
#define PURPLE                         0x6875
#define PURPLE_WEB                     0x8010
#define PURPLE_MUNSELL                 0x9818
#define PURPLE_X11                     0xa11e
#define PURPLE_MOUNTAIN_MAJESTY        0x93d6
#define PURPLE_NAVY                    0x4a90
#define PURPLE_PIZZAZZ                 0xfa7b
#define PURPLE_PLUM                    0x9a96
#define PURPUREUS                      0x9a75
#define QUEEN_BLUE                     0x4352
#define QUEEN_PINK                     0xee7a
#define QUICK_SILVER                   0xa534
#define QUINACRIDONE_MAGENTA           0x89cb
#define RADICAL_RED                    0xf9ab
#define RAISIN_BLACK                   0x2104
#define RAJAH                          0xfd4c
#define RASPBERRY                      0xe04b
#define RASPBERRY_GLACE                0x92ed
#define RASPBERRY_ROSE                 0xb22d
#define RAW_SIENNA                     0xd44b
#define RAW_UMBER                      0x8328
#define RAZZLE_DAZZLE_ROSE             0xf999
#define RAZZMATAZZ                     0xe12d
#define RAZZMIC_BERRY                  0x8a70
#define REBECCA_PURPLE                 0x6193
#define RED                            0xf800
#define RED_CRAYOLA                    0xe909
#define RED_MUNSELL                    0xf007
#define RED_NCS                        0xc006
#define RED_PANTONE                    0xe947
#define RED_PIGMENT                    0xe8e4
#define RED_RYB                        0xf922
#define RED_ORANGE                     0xfa89
#define RED_ORANGE_CRAYOLA             0xfb43
#define RED_ORANGE_COLOR_WHEEL         0xfa20
#define RED_PURPLE                     0xe00f
#define RED_SALSA                      0xf9c9
#define RED_VIOLET                     0xc0b0
#define RED_VIOLET_CRAYOLA             0xc231
#define RED_VIOLET_COLOR_WHEEL         0x9147
#define REDWOOD                        0xa2ca
#define RESOLUTION_BLUE                0x0110
#define RHYTHM                         0x73b2
#define RICH_BLACK                     0x0208
#define RICH_BLACK_FOGRA29             0x0042
#define RICH_BLACK_FOGRA39             0x0000
#define RIFLE_GREEN                    0x4267
#define ROBIN_EGG_BLUE                 0x0679
#define ROCKET_METALLIC                0x8bf0
#define ROJO_SPANISH_RED               0xa880
#define ROMAN_SILVER                   0x8452
#define ROSE                           0xf80f
#define ROSE_BONBON                    0xfa13
#define ROSE_DUST                      0x9aed
#define ROSE_EBONY                     0x6248
#define ROSE_MADDER                    0xe126
#define ROSE_PINK                      0xfb39
#define ROSE_POMPADOUR                 0xebd3
#define ROSE_QUARTZ                    0xacd5
#define ROSE_RED                       0xc0ea
#define ROSE_TAUPE                     0x92eb
#define ROSE_VALE                      0xaa6a
#define ROSEWOOD                       0x6001
#define ROSSO_CORSA                    0xd000
#define ROSY_BROWN                     0xbc71
#define ROYAL_BLUE_DARK                0x010c
#define ROYAL_BLUE_LIGHT               0x435c
#define ROYAL_PURPLE                   0x7a95
#define ROYAL_YELLOW                   0xfecb
#define RUBER                          0xca2e
#define RUBINE_RED                     0xd00a
#define RUBY                           0xe08b
#define RUBY_RED                       0x9883
#define RUFOUS                         0xa8e0
#define RUSSET                         0x8223
#define RUSSIAN_GREEN                  0x648c
#define RUSSIAN_VIOLET                 0x30a9
#define RUST                           0xb201
#define RUSTY_RED                      0xd968
#define SACRAMENTO_STATE_GREEN         0x01c4
#define SADDLE_BROWN                   0x8a22
#define SAFETY_ORANGE                  0xfbc0
#define SAFETY_ORANGE_BLAZE_ORANGE     0xfb20
#define SAFETY_YELLOW                  0xee80
#define SAFFRON                        0xf626
#define SAGE                           0xbdd1
#define ST._PATRICK_S_BLUE             0x214f
#define SALMON                         0xfc0e
#define SALMON_PINK                    0xfc94
#define SAND                           0xc590
#define SAND_DUNE                      0x9382
#define SANDY_BROWN                    0xf52c
#define SAP_GREEN                      0x53e5
#define SAPPHIRE                       0x0a97
#define SAPPHIRE_BLUE                  0x0334
#define SAPPHIRE_CRAYOLA               0x0334
#define SATIN_SHEEN_GOLD               0xcd06
#define SCARLET                        0xf920
#define SCHAUSS_PINK                   0xfc95
#define SCHOOL_BUS_YELLOW              0xfec0
#define SCREAMIN__GREEN                0x67ec
#define SEA_GREEN                      0x2c4a
#define SEA_GREEN_CRAYOLA              0x07f9
#define SEAL_BROWN                     0x5921
#define SEASHELL                       0xffbd
#define SELECTIVE_YELLOW               0xfdc0
#define SEPIA                          0x7202
#define SHADOW                         0x8bcb
#define SHADOW_BLUE                    0x7454
#define SHAMROCK_GREEN                 0x04ec
#define SHEEN_GREEN                    0x8ea0
#define SHIMMERING_BLUSH               0xdc32
#define SHINY_SHAMROCK                 0x5d2f
#define SHOCKING_PINK                  0xf878
#define SHOCKING_PINK_CRAYOLA          0xfb7f
#define SIENNA                         0x8962
#define SILVER                         0xc618
#define SILVER_CRAYOLA                 0xce17
#define SILVER_METALLIC                0xad55
#define SILVER_CHALICE                 0xad75
#define SILVER_PINK                    0xc575
#define SILVER_SAND                    0xbe18
#define SINOPIA                        0xca01
#define SIZZLING_RED                   0xf9ca
#define SIZZLING_SUNRISE               0xfec0
#define SKOBELOFF                      0x03ae
#define SKY_BLUE                       0x867d
#define SKY_BLUE_CRAYOLA               0x76bd
#define SKY_MAGENTA                    0xcb95
#define SLATE_BLUE                     0x6ad9
#define SLATE_GRAY                     0x7412
#define SLIMY_GREEN                    0x2ca2
#define SMITTEN                        0xca10
#define SMOKY_BLACK                    0x1061
#define SNOW                           0xffdf
#define SOLID_PINK                     0x89c8
#define SONIC_SILVER                   0x73ae
#define SPACE_CADET                    0x194a
#define SPANISH_BISTRE                 0x83a6
#define SPANISH_BLUE                   0x0397
#define SPANISH_CARMINE                0xd008
#define SPANISH_GRAY                   0x9cd3
#define SPANISH_GREEN                  0x048a
#define SPANISH_ORANGE                 0xeb00
#define SPANISH_PINK                   0xf5f7
#define SPANISH_RED                    0xe004
#define SPANISH_SKY_BLUE               0x07ff
#define SPANISH_VIOLET                 0x4950
#define SPANISH_VIRIDIAN               0x03eb
#define SPRING_BUD                     0xa7e0
#define SPRING_FROST                   0x87e5
#define SPRING_GREEN                   0x07ef
#define SPRING_GREEN_CRAYOLA           0xef57
#define STAR_COMMAND_BLUE              0x03d7
#define STEEL_BLUE                     0x4416
#define STEEL_PINK                     0xc999
#define STEEL_TEAL                     0x5c51
#define STIL_DE_GRAIN_YELLOW           0xfecb
#define STRAW                          0xe6cd
#define STRAWBERRY                     0xfa8a
#define STRAWBERRY_BLONDE              0xfc8c
#define SUGAR_PLUM                     0x926e
#define SUNGLOW                        0xfe66
#define SUNRAY                         0xe54a
#define SUNSET                         0xfeb4
#define SUPER_PINK                     0xcb55
#define SWEET_BROWN                    0xa9a6
#define SYRACUSE_ORANGE                0xd220
#define TAN                            0xd5b1
#define TAN_CRAYOLA                    0xdccd
#define TANGERINE                      0xf420
#define TANGO_PINK                     0xe38f
#define TART_ORANGE                    0xfa68
#define TAUPE                          0x49e6
#define TAUPE_GRAY                     0x8c31
#define TEA_GREEN                      0xd798
#define TEA_ROSE                       0xfc0f
#define TEA_ROSE                       0xf618
#define TEAL                           0x0410
#define TEAL_BLUE                      0x33b1
#define TELEMAGENTA                    0xc9ae
#define TENNE_TAWNY                    0xcaa0
#define TERRA_COTTA                    0xe38b
#define THISTLE                        0xddfb
#define THULIAN_PINK                   0xdb74
#define TICKLE_ME_PINK                 0xfc55
#define TIFFANY_BLUE                   0x0dd6
#define TIMBERWOLF                     0xdeba
#define TITANIUM_YELLOW                0xef20
#define TOMATO                         0xfb08
#define TROPICAL_RAINFOREST            0x03ab
#define TRUE_BLUE                      0x2b58
#define TRYPAN_BLUE                    0x1836
#define TUFTS_BLUE                     0x3c7b
#define TUMBLEWEED                     0xdd51
#define TURQUOISE                      0x471a
#define TURQUOISE_BLUE                 0x07fd
#define TURQUOISE_GREEN                0xa6b6
#define TURTLE_GREEN                   0x8ccb
#define TUSCAN                         0xfeb4
#define TUSCAN_BROWN                   0x6a66
#define TUSCAN_RED                     0x7a49
#define TUSCAN_TAN                     0xa3cb
#define TUSCANY                        0xc4d3
#define TWILIGHT_LAVENDER              0x8a4d
#define TYRIAN_PURPLE                  0x6007
#define UA_BLUE                        0x0195
#define UA_RED                         0xd809
#define ULTRAMARINE                    0x381f
#define ULTRAMARINE_BLUE               0x433e
#define ULTRA_PINK                     0xfb7f
#define ULTRA_RED                      0xfb70
#define UMBER                          0x6288
#define UNBLEACHED_SILK                0xfef9
#define UNITED_NATIONS_BLUE            0x5c9c
#define UNIVERSITY_OF_PENNSYLVANIA_RED 0xa004
#define UNMELLOW_YELLOW                0xffec
#define UP_FOREST_GREEN                0x0224
#define UP_MAROON                      0x7882
#define UPSDELL_RED                    0xa905
#define URANIAN_BLUE                   0xaede
#define USAFA_BLUE                     0x0273
#define VAN_DYKE_BROWN                 0x6205
#define VANILLA                        0xf735
#define VANILLA_ICE                    0xf475
#define VEGAS_GOLD                     0xc58b
#define VENETIAN_RED                   0xc842
#define VERDIGRIS                      0x4595
#define VERMILION                      0xe206
#define VERMILION                      0xd9c3
#define VERONICA                       0xa11e
#define VIOLET                         0x881f
#define VIOLET_COLOR_WHEEL             0x781f
#define VIOLET_CRAYOLA                 0x91ef
#define VIOLET_RYB                     0x8015
#define VIOLET_WEB                     0xec1d
#define VIOLET_BLUE                    0x3256
#define VIOLET_BLUE_CRAYOLA            0x7379
#define VIOLET_RED                     0xf292
#define VIRIDIAN                       0x440d
#define VIRIDIAN_GREEN                 0x04b3
#define VIVID_BURGUNDY                 0x98e6
#define VIVID_SKY_BLUE                 0x067f
#define VIVID_TANGERINE                0xfd11
#define VIVID_VIOLET                   0x981f
#define VOLT                           0xcfe0
#define WARM_BLACK                     0x0208
#define WHEAT                          0xf6f6
#define WHITE                          0xffff
#define WILD_BLUE_YONDER               0xa57a
#define WILD_ORCHID                    0xd394
#define WILD_STRAWBERRY                0xfa14
#define WILD_WATERMELON                0xfb70
#define WINDSOR_TAN                    0xa2a0
#define WINE                           0x7166
#define WINE_DREGS                     0x6188
#define WINTER_SKY                     0xf80f
#define WINTERGREEN_DREAM              0x544f
#define WISTERIA                       0xcd1b
#define WOOD_BROWN                     0xc4cd
#define XANADU                         0x742f
#define XANTHIC                        0xef61
#define XANTHOUS                       0xf5a5
#define YALE_BLUE                      0x01ad
#define YELLOW                         0xffe0
#define YELLOW_CRAYOLA                 0xff50
#define YELLOW_MUNSELL                 0xee60
#define YELLOW_NCS                     0xfe80
#define YELLOW_PANTONE                 0xfee0
#define YELLOW_PROCESS                 0xff60
#define YELLOW_RYB                     0xffe6
#define YELLOW_GREEN                   0x9e66
#define YELLOW_GREEN_CRAYOLA           0xc710
#define YELLOW_GREEN_COLOR_WHEEL       0x3583
#define YELLOW_ORANGE                  0xfd68
#define YELLOW_ORANGE_COLOR_WHEEL      0xfca0
#define YELLOW_SUNSHINE                0xffa0
#define YINMN_BLUE                     0x2a92
#define ZAFFRE                         0x00b5
#define ZOMP                           0x3d31
